export RANKING_SYSTEM_HOME=$(pwd)

export LC_ALL=C
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$RANKING_SYSTEM_HOME/UbjsonCpp/src/
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$RANKING_SYSTEM_HOME/config_loader/
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$RANKING_SYSTEM_HOME/common/

export SOUTH_PORT=15000
export RANKING_PORT=16000
export INDEX_PORT=14000
export FORWARD_PORT=17000

export MAIN_EXPORTS_ARE_DONE=1
